// Code generated by "stringer -type=Level"; DO NOT EDIT.

package log

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN-0]
	_ = x[EMERGENCY-1]
	_ = x[ALERT-2]
	_ = x[CRITICAL-3]
	_ = x[ERROR-4]
	_ = x[WARNING-5]
	_ = x[NOTICE-6]
	_ = x[INFO-7]
	_ = x[DEBUG-8]
}

const _Level_name = "UNKNOWNEMERGENCYALERTCRITICALERRORWARNINGNOTICEINFODEBUG"

var _Level_index = [...]uint8{0, 7, 16, 21, 29, 34, 41, 47, 51, 56}

func (i Level) String() string {
	if i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
